#if !defined(AFX_LAMEENCODERX_H__094D5056_C5C4_11D3_8290_0080C605ADA4__INCLUDED_)
#define AFX_LAMEENCODERX_H__094D5056_C5C4_11D3_8290_0080C605ADA4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLameEncoderX wrapper class

class CLameEncoderX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CLameEncoderX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xcea71983, 0xc458, 0x11d3, { 0x82, 0x90, 0x0, 0x80, 0xc6, 0x5, 0xad, 0xa4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetInputFile();
	void SetInputFile(LPCTSTR);
	CString GetOutputFile();
	void SetOutputFile(LPCTSTR);
	long GetEncodingPriority();
	void SetEncodingPriority(long);
	long GetMode();
	void SetMode(long);
	long GetBitrate();
	void SetBitrate(long);
	float GetSamplingFreq();
	void SetSamplingFreq(float);
	BOOL GetVoiceMode();
	void SetVoiceMode(BOOL);
	BOOL GetUseVBR();
	void SetUseVBR(BOOL);
	long GetVBRQuality();
	void SetVBRQuality(long);
	long GetMinimumBitrate();
	void SetMinimumBitrate(long);
	long GetMaximumBitrate();
	void SetMaximumBitrate(long);
	BOOL GetDisableVBRInfoTag();
	void SetDisableVBRInfoTag(BOOL);
	BOOL GetUseQualityImprovements();
	void SetUseQualityImprovements(BOOL);
	BOOL GetUseFastMode();
	void SetUseFastMode(BOOL);
	BOOL GetDisableSFBCutoff();
	void SetDisableSFBCutoff(BOOL);
	BOOL GetAllowChanDifBlockTypes();
	void SetAllowChanDifBlockTypes(BOOL);
	BOOL GetOnlyATHForMasking();
	void SetOnlyATHForMasking(BOOL);
	BOOL GetNoShortBlocks();
	void SetNoShortBlocks(BOOL);
	BOOL GetInputIsRawPCM();
	void SetInputIsRawPCM(BOOL);
	BOOL GetForceByteSwab();
	void SetForceByteSwab(BOOL);
	BOOL GetDownmixToMono();
	void SetDownmixToMono(BOOL);
	BOOL GetErrorProtection();
	void SetErrorProtection(BOOL);
	BOOL GetMarkAsCopyrighted();
	void SetMarkAsCopyrighted(BOOL);
	BOOL GetMarkAsNonOriginal();
	void SetMarkAsNonOriginal(BOOL);
	CString GetTitle();
	void SetTitle(LPCTSTR);
	CString GetArtist();
	void SetArtist(LPCTSTR);
	CString GetAlbum();
	void SetAlbum(LPCTSTR);
	CString GetYear();
	void SetYear(LPCTSTR);
	CString GetComment();
	void SetComment(LPCTSTR);
	CString GetGenre();
	void SetGenre(LPCTSTR);
	float GetResampleFreq();
	void SetResampleFreq(float);
	float GetEnoderXVersion();
	void SetEnoderXVersion(float);

// Operations
public:
	BOOL StartEncode();
	CString GetCurrentCommandString();
	void SetAllDefaultParams();
	CString GetTotalEncodingTime();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LAMEENCODERX_H__094D5056_C5C4_11D3_8290_0080C605ADA4__INCLUDED_)
